protocols:
    protocolData:
      - protocolName: "zeroswap"
        chainName: "ethereum"
        contractAddress: "0xEDF822c90d62aC0557F8c4925725A2d6d6f17769"
        walletAddress: ""
        rpc: "https://cloudflare-eth.com"
        stake:
          requiredArray: ["stake","true","false"]
        unstake:
          requiredArray: ["unstake","false","false"]

      - protocolName: "zeroswap"
        chainName: "binance"
        contractAddress: "0x593497878c33dd1f32098E3F4aE217773F803cf3"
        walletAddress: ""
        rpc: "https://bsc-dataseed.binance.org/"
        stake:
          requiredArray: ["stake","true","false"]
        unstake:
          requiredArray: ["unstake","false","false"]

      - protocolName: "zeroswap"
        chainName: "polygon"
        contractAddress: "0x89eA093C07f4FCc03AEBe8A1D5507c15dE88531f"
        walletAddress: ""
        rpc: "https://polygon-rpc.com"
        stake:
          requiredArray: ["stake","true","false"]
        unstake:
          requiredArray: ["unstake","false","false"]

      - protocolName: "zeroswap"
        chainName: "avalanche"
        contractAddress: "0xa4751EAa89C5D6ff61384766268cabf25aCD1011"
        walletAddress: ""
        rpc: "https://rpc.ankr.com/avalanche"
        stake:
          requiredArray: ["stake","true","false"]
        unstake:
          requiredArray: ["unstake","false","false"]

      - protocolName: "opendao"
        chainName: "ethereum"
        contractAddress: "0xEDd27C961CE6f79afC16Fd287d934eE31a90D7D1"
        walletAddress: ""
        rpc: "https://eth-mainnet.public.blastapi.io"
        stake:
          requiredArray: ["enter","true","false"]
        unstake:
          requiredArray: ["leave","true","false"]

      - protocolName: "pancake"
        chainName: "binance"
        contractAddress: "0x45c54210128a065de780C4B0Df3d16664f7f859e"
        walletAddress: ""
        rpc: "https://bsc-dataseed.binance.org/"
        stake:
          requiredArray: ["deposit","true","true"]
        unstake:
          requiredArray: ["withdraw","true","false"]
      
      - protocolName: "apeswap"
        chainName: "binance"
        contractAddress: "0x5c8D727b265DBAfaba67E050f2f739cAeEB4A6F9"
        walletAddress: ""
        rpc: "https://bsc-dataseed.binance.org/"
        stake:
          requiredArray: ["enterStaking","true","false"]
        unstake:
          requiredArray: ["leaveStaking","true","false"]
        